# Generated by Django 5.0.4 on 2024-05-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('product_category', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('restock_level', models.IntegerField()),
            ],
        ),
    ]
