# Generated by Django 5.0.4 on 2024-06-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nkapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Prod',
        ),
        migrations.RenameField(
            model_name='prod',
            old_name='product_category',
            new_name='prod_category',
        ),
        migrations.RenameField(
            model_name='prod',
            old_name='product_id',
            new_name='prod_id',
        ),
        migrations.RenameField(
            model_name='prod',
            old_name='product_name',
            new_name='prod_name',
        ),
        migrations.RenameField(
            model_name='prod',
            old_name='product_price',
            new_name='prod_price',
        ),
    ]
