# Generated by Django 5.0.4 on 2024-04-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=30)),
                ('Lastname', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=30)),
            ],
        ),
    ]
