# Generated by Django 5.0.4 on 2024-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=35)),
                ('Designation', models.CharField(max_length=35)),
                ('Employment_date', models.CharField(max_length=35)),
                ('Age', models.CharField(max_length=35)),
                ('Gender', models.CharField(max_length=35)),
            ],
        ),
    ]
