# Generated by Django 5.0.4 on 2024-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Next_of_Kin',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Salary',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
