# Generated by Django 5.0.4 on 2024-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='EmailAddress',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
