# Generated by Django 5.0.4 on 2024-05-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_delete_teacher_student_emailaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=35)),
                ('Price', models.CharField(max_length=35)),
                ('Quantity', models.CharField(max_length=35)),
                ('Expirydate', models.CharField(max_length=35)),
            ],
        ),
    ]
