# Generated by Django 5.0.4 on 2024-06-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.IntegerField()),
                ('recorder_level', models.IntegerField()),
                ('reorder_quantity', models.IntegerField()),
                ('safety_stock_level', models.IntegerField()),
                ('leadtime', models.DateField()),
                ('storage_location', models.CharField(max_length=100)),
                ('batch_number', models.IntegerField()),
                ('expiry_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PricingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('discounts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('sku', models.IntegerField()),
                ('upc', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesorder_id', models.IntegerField()),
                ('customer_id', models.IntegerField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('order_quantity', models.IntegerField()),
                ('sales_channel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(max_length=100)),
                ('delivery_terms', models.CharField(max_length=100)),
                ('supplier_rating', models.CharField(max_length=100)),
            ],
        ),
    ]
