# Generated by Django 5.0.4 on 2024-06-22 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorydetails',
            old_name='recorder_level',
            new_name='reorder_level',
        ),
    ]
